//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenDi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenDi()
        {
            this.HinhAnhChuyenDis = new HashSet<HinhAnhChuyenDi>();
            this.KhoanChiTieux = new HashSet<KhoanChiTieu>();
            this.KhoanThus = new HashSet<KhoanThu>();
            this.ThamGiaChuyenDis = new HashSet<ThamGiaChuyenDi>();
        }
    
        public int IDChuyenDi { get; set; }
        public string TenChuyenDi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string GioiThieu { get; set; }
        public string LoTrinh { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhChuyenDi> HinhAnhChuyenDis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoanChiTieu> KhoanChiTieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoanThu> KhoanThus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGiaChuyenDi> ThamGiaChuyenDis { get; set; }
    }
}
