//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWeSplitEntities : DbContext
    {
        public DBWeSplitEntities()
            : base("name=DBWeSplitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenDi> ChuyenDis { get; set; }
        public virtual DbSet<HinhAnhChuyenDi> HinhAnhChuyenDis { get; set; }
        public virtual DbSet<KhoanChiTieu> KhoanChiTieux { get; set; }
        public virtual DbSet<KhoanThu> KhoanThus { get; set; }
        public virtual DbSet<ThamGiaChuyenDi> ThamGiaChuyenDis { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
    }
}
